### ISSUE TITLE
2FA QR code not visible in email sent to new user

### ISSUE THREAD

**Issue by ericraskin** [d3vilh/openvpn-ui#104]
Maybe I'm missing something...

When I create a new certificate using MFA and generate an email to send to the new user, the QR code is not included in the email.

How does the user get the QR code to put into their authenticator app?

There is also no attachment containing the .ovpn file.  Maybe it has something to do with using Gmail?

![image](https://github.com/user-attachments/assets/c53141fc-be92-46c6-aa91-99c6529e6b63)

**Comment by d3vilh** [comment]
Hey @ericraskin you are not missing, this is limitation on `mailto:` protocol.
In short, to automatically copy-paste QR code we have to implement own mail server which overcomplicate that project.

Similar issue #39 

I just copy and paste QR code to email body.
