### ISSUE TITLE
fix this application

### ISSUE THREAD

**Issue by kathuluman** [d3vilh/openvpn-ui#111]
does not work

**Comment by hanselsen** [comment]
@kathuluman This is not the way you request support from an open source project. Perhaps you should find a paid alternative.

**Comment by kathuluman** [comment]
Bro screw off fr

**Comment by d3vilh** [comment]
Im very much engaged with other project which brings main income to my family, at the moment.

Can have a look on your issue while on Christmas holidays. 

Please share `docker logs openvpn-ui && docker logs openvpn-server` here.
