### ISSUE TITLE
How to refresh certificates - for server and client?

### ISSUE THREAD

**Issue by PennyLook** [d3vilh/openvpn-ui#12]
Hello,
On the `/certificates` page we have a preview of the certificates. There is an `Expiration` date after which the client/server will probably not have access to the VPN. I'm referring to these dates:

![image](https://github.com/d3vilh/openvpn-ui/assets/19575209/518b52fa-f9a4-4089-aaee-441506ecd313)

How do you refresh these certificates? Is it possible to do it somehow without breaking the current server<->client connection e.g. by swapping `.ovpn` config on client and server?

**Comment by d3vilh** [comment]
for the clients you can do [with `renew` feature](https://github.com/d3vilh/openvpn-ui#renew-certificates-for-client-profiles). 
Server itself (CA) is not possible to renew, the only way is to create CA with infinite expiration time (lets say 99 years) or generate new CA.
