### ISSUE TITLE
Clients certificates

### ISSUE THREAD

**Issue by linzp007** [d3vilh/openvpn-ui#2]
thanks for your awesome job, 

but when i download Clients certificates, I got this error reponse:

`This site can’t be reached

The webpage at http://127.0.0.1:8080/certificates/test might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE`

Some error message could be found backend:

./easyrsa: 341: set: Illegal option -o echo
openvpn    | Generate HMAC signature...
openvpn    | Create certificate revocation list (CRL)...
openvpn    | Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
openvpn    | Using configuration from /opt/app/easy-rsa/pki/easy-rsa-160.sH7Gw1/tmp.EdSeKW
openvpn    | ./easyrsa: 341: set: Illegal option -o echo
openvpn    | Configuring networking rules...
openvpn    | net.ipv4.ip_forward = 1
openvpn    | Configuring iptables...
openvpn    | NAT for OpenVPN clients
openvpn    | Bad argument 'ovpn_trusted_subnet'
openvpn    | Try 'iptables -h' or 'iptables --help' for more information.

Look forward to your answser..

**Comment by d3vilh** [comment]
Hi @linzp007 thanks for reporting.
Could you tell me which docker image do you use for OpenVPN-UI and OpenVPN setup?

Meanwhile I'll try to reproduce it with latest builds for intel and arm.

**Comment by linzp007** [comment]
I use amd64 image , and the latest version
just motified the username, password in the compose yml
but I got still the same error

**Comment by d3vilh** [comment]
Good news is Im able to reproduce it, but it will take some time to debug.

**Comment by d3vilh** [comment]
OK, seems it was fixed, so Im closing it.
