### ISSUE TITLE
Problem connection dynamic.pool (v0.8)

### ISSUE THREAD

**Issue by BliNeR-KeY** [d3vilh/openvpn-ui#22]
Hello i have small problem in my debian server
maybe need a help.
i'm create users from UI. only username/password
/root/openvpn/staticclients/myVPNUSER 
ifconfig-push dynamic.pool 255.255.255.0

server.conf are default by you. 

other one question.
how to update V0.9 without lost my data ?

**Comment by d3vilh** [comment]
Hi @BliNeR-KeY 
Thanks for reporting. it is a bug.

I just retest and confirm it is still there in [ver 0.9 ](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9)which I just release couple of minutes ago.

```shell
philipp@d3vpi:~/openvpn-server/staticclients $ cat dyno-pass
ifconfig-push dynamic.pool 255.255.255.0
philipp@d3vpi:~/openvpn-server/staticclients $
```

As workaround you can delete this configuration file manually. I'll include fix and rebuild images tomorrow.

Thanks a lot!

**Comment by d3vilh** [comment]
it is confirmed to be fixed and images were already rebuilt.
You can pull tag `latest` or `0.9` I decided to quickly fix and push into the same branch.

Here is image ids with fixed bug:
```shell
REPOSITORY          TAG              IMAGE ID       CREATED          SIZE
d3vilh/openvpn-ui   0.9-arm32v5      1549715d4aa4   4 minutes ago    44.1MB
d3vilh/openvpn-ui   0.9-amd64        db026083f460   24 minutes ago   47.2MB
d3vilh/openvpn-ui   0.9-arm64        31e575ebabf5   37 minutes ago   49.3MB
```

Closing now as "fixed", please reopen if you think it was not 😎

**Comment by BliNeR-KeY** [comment]
Thank you so much for you support and really
Is the best OPENVPN Ui i try too many..

I will let you know tomorrow.
Is my first time using docker and I need first understand 😅😅😅

Its about upgrade take files take directly in github or what.. 

docker for me are totally new.. 
Im Developer in enigma2 admin/dev in EGAMI images this hobby never make us bored 😅

**Comment by d3vilh** [comment]
> ts about upgrade take files take directly in github or what..

Here is [upgrade](https://github.com/d3vilh/openvpn-ui#upgrade-to-new-version) procedure. 
As you are going to upgrade from `0.8` to `0.9` - there is no DB schema changes and you can skip **`Verification`** step.

Just do **`Backup`**(just in case) and then [**`Upgrade`**](https://github.com/d3vilh/openvpn-ui#upgrade) itself.
