### ISSUE TITLE
repository for d3vilh/openvpn-server Docker image

### ISSUE THREAD

**Issue by pishangujeniya** [d3vilh/openvpn-ui#23]
I have seen that all the documents contain the link to the docker image for `d3vilh/openvpn-server`, but didn't find the real repository for it.

Instead of having a link to the docker hub, its better to put the GitHub repository link and in the `README.md` of that repository put the badge to the docker hub for example: 

[![Docker Image Version (latest semver)](https://img.shields.io/docker/v/d3vilh/openvpn-server?label=Docker)](https://hub.docker.com/r/d3vilh/openvpn-server)

**Comment by d3vilh** [comment]
Hi @pishangujeniya!
Well, the image itself building during installation if of [**OpenVPN-AWS**](https://github.com/d3vilh/openvpn-aws) project (Here is [direct image build link](https://github.com/d3vilh/openvpn-aws/tree/master/openvpn/openvpn-docker)), or [**Raspberry-Gateway** ](https://github.com/d3vilh/raspberry-gateway) ([direct link](https://github.com/d3vilh/raspberry-gateway/tree/master/openvpn-server/openvpn-docker)).

Both projects installs both Openvpn and Openvpn-ui containers in tandem.
If you are interesting in x86/amd64 then you should go with openvpn-aws, for Raspberry-pi - Raspberry-Gateway.

I though to have detached GitHub repo for openvpn-server image and I'll probably do.

For now, [Here is link](https://hub.docker.com/r/d3vilh/openvpn-server) to the Docker hub where I keep the latest server images.

Thank you for suggestion, I'll add this badge shields too.

**Comment by pishangujeniya** [comment]
@d3vilh  Thank you for clarifying the source code of OpenVPN Server image.

**Comment by d3vilh** [comment]
Finally. [Here is detached OpenVPN-Server repo](https://github.com/d3vilh/openvpn-server).
Thank you for shields update suggestion. It's embedded now..
