### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by dinger1986** [d3vilh/openvpn-ui#25]
Hello,

Are you planning on adding MFA integration for OpenVPN?

Thanks

**Comment by d3vilh** [comment]
Hi @dinger1986,
This needs backend container support and new options to pass when generating new Certificate.

I like your suggestion, this definitely will be included in one of the future versions.

**Comment by d3vilh** [comment]
@dinger1986 MFA is part of `dev` branch and will be included in next `0.9.3` release after I'll complete my testing.

**Comment by dinger1986** [comment]
if theres a guide for testing more than happy giving dev a test if that helps? Probably not worth your time writing it.

Also as a side, maybe worth looking at hanging your license as MIT is very permissive

**Comment by d3vilh** [comment]
> if theres a guide for testing more than happy giving dev a test if that helps? Probably not worth your time writing it.
> 
> Also as a side, maybe worth looking at hanging your license as MIT is very permissive

I pushed [0.9.3 ](https://hub.docker.com/layers/d3vilh/openvpn-ui/0.9.3/images/sha256-4a2d2e2f3a1186cee4bf54ec5de03d111ce96edda87ca50108b5700da3008822?context=explore)release candidate this morning on Docker hub. MFA will works fine in pair with updated [openvpn-server](https://github.com/d3vilh/openvpn-server) version, image [I pushed on hub](https://hub.docker.com/layers/d3vilh/openvpn-server/latest/images/sha256-d1a0610d4f173ccd7262474bf7394f9e64891bdb38d7eafdf91a050c2538f897?context=explore) yesterday

[Here is](https://github.com/d3vilh/openvpn-ui#two-factor-authentication-2fa) documentation draft.

I did my tests and it seems works fine, but im sure there are hidden bugs :)

**Comment by dinger1986** [comment]
great, Ill give it a test and can write up an install script once https://github.com/d3vilh/openvpn-ui/issues/26 is done as well :)

**Comment by d3vilh** [comment]
closing it as implemented

**Comment by dinger1986** [comment]
thanks
