### ISSUE TITLE
EASY-RSA feature request, UI container restart not working properly and administrative port for the OpenVPN container

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#31]
Hello again :)

* I would like to suggest a feature, if possible that the openvpn-ui contaienr, upon initialization would either read the vars file in config or the pki directories instead of having to use the UI for that (will save me a gazillion of time, if possible :) )

* When clicking on the "Restart UI" button from maintenance, the openvpn-ui contaienr doesn't restart, it stops but doesn't restart

* In the example docker-compose.yml please add port 2080 in the openvpn section for administrative purposes

Thanks a lot for this project

**Comment by TheAlbanian** [comment]
> Hello again :)
> 

> * When clicking on the "Restart UI" button from maintenance, the openvpn-ui contaienr doesn't restart, it stops but doesn't restart

hello i have noted https://github.com/d3vilh/openvpn-server it no restart.

but using https://github.com/d3vilh/openvpn-aws it works as well.

**Comment by d3vilh** [comment]
Hi @reamasesa new line in compose file added, if you would like to share management port outside, just uncomment it. 

Hello @TheAlbanian thank you for reporting this, I'll have a look on it and provide the fix later.
