### ISSUE TITLE
Prometheus endpoint

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#35]
Hello and thank you for all this great great work!!!! :)

I was wondering if it's possible to have a Prometheus endpoint that will either enable the openvpn-exporter to connect to it and do its magic or have the endpoint itself publish the metrics, we're currently monitoring for up (obviously :D) and number of online users (very small deployment, not sure what else is needed or can be published)
I was thinking that for the UI maybe we can have the number of users, certificates (revoked or otherwise) and such

It would be great if this can be made possible

Thanks again

**Comment by d3vilh** [comment]
Hi @reamasesa,[ I have own exporter ](https://github.com/d3vilh/openvpn-exporter)for this for [ARM setup](https://github.com/d3vilh/raspberry-gateway). 
But will include it as option in [openvpn-aws ](https://github.com/d3vilh/openvpn-aws), all together with Grafana, Dashboard and DB instance to store all the data.

**Comment by d3vilh** [comment]
It is drafted in [openvpn-aws/dev ](https://github.com/d3vilh/openvpn-aws/tree/dev)branch.
You have to edit config.yml for this options:
```shell
# OpenVPN monitoring configuration.             # Requires `monitoring_enable`
monitoring_enable: false                        # Set true to enable OpenVPN Server monitoring
monitoring_grafana_admin_password: "admin"      # Is only used the first time when Grafana starts up
monitoring_days_keep_interval: 90d              # How long to keep data in Prometheus DB (decrease if you have less than 5Gb of free disk space)
```
set `monitoring_enable` to `true` and run `ansible-playbook main.yml`, as result, you'll have Prom + Exporter and Grafana + Dashboard.

Beware, that this is default Dashboard, it may lack of some stats (Server status at the moment does not works, for example), will change it in future commits.

**Comment by reamasesa** [comment]
Thank you very much :)
