### ISSUE TITLE
Issue with creating certificate

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#38]
Hello,

When setting the EasyRSA with a value that has a special character, in this case a period, creation of certificate fails
I've added the "Ltd." to my EasyRSA_REQ_ORG and now when I try to create a certificate I get "Exit status 1"
The logs show this message

`openvpn-ui | 2023/12/06 12:07:51.533 [D] [certificates.go:157]  /bin/bash: line 1: export: `Ltd.': not a valid identifier`

Thanks

**Comment by d3vilh** [comment]
Hi @reamasesa 
Thanks for reporting it. Did you try without dot at the end - `Ltd`? 
It may be related to back-end bash script which may interpritate . as a special character.
Im curious how did you update the this var - with OpenVPN-UI or configuration file. 
Interesting, what happens if you'll try this way `Ltd\.`.

**Comment by d3vilh** [comment]
Hi @reamasesa it is fixed in dev.
I'll combine bug fix in the next release all together with the rest bug fixes.

Thank you for reporting, once again!

**Comment by reamasesa** [comment]
> Hi @reamasesa it is fixed in dev. I'll combine bug fix in the next release all together with the rest bug fixes.
> 
> Thank you for reporting, once again!

Thank you very much, sorry for the late replies

I'm trying to use the UI for everything (although I would have liked the option to pre-set the EasyRSA variables for easier deployment), I only checked "Ltd." and "Ltd"


Thanks again

**Comment by d3vilh** [comment]
Closed as fixed in [0.9.4.1](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9.4.1)
