### ISSUE TITLE
Email issue and request

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#39]
Hi,

* When using the "Send email`, I only get some information about the certificate, not the detailed information I get when I click on the `Copy` button, which incidentally, doesn't copy the QR code
`2FA Name: Blah
Certificate Name:
Blah
Status: Valid
Expiration Time: 2026-03-10 12:16
Revoke Time: Not Revoked
IP Address: dynamic.pool
Serial: Blah
Registered e-mail: Blah@Blah.com
Registered Country: Blah
Registered State/Region: Blah
Registered City: Blah
Registered Organisation: Blah
Registered Unit: Blah
Two Factor Authorisation (2FA) QR Code:                           
                            
                              
                            
                          
                        `
* Can you add an option to email the configuration to the end user, as well?

Thanks

**Comment by d3vilh** [comment]
@reamasesa hello again :)
yes, this is one of the challenge I had during coding this functionality. 
I can't figure out how to insert QR code into the mail body the way it will attach as image but not the binary.
Here is [the piece of code](https://github.com/d3vilh/openvpn-ui/blob/273fb57f3d684a0465b3608782de5ea3abb6d16a/views/certificates.html#L408C14-L408C14) which currently commented out. It's a good idea to drop JS and do all this on the server side with Go, but it demands time, which Im currently  lacking. 

Appreciate community help with this.

**Comment by permanutry** [comment]
I actually had the same request.
Will have a look on this code on the week, probably will found some solution and push pull request to you 😎

**Comment by d3vilh** [comment]
it will not be implemented due to limitations of mailto: protocol which does not support any type of attachments.

As alternate way we may use internal SMTP server or 3P server to sending emails, but this will overcomplicate all the solution.

**Comment by reamasesa** [comment]
> it will not be implemented due to limitations of mailto: protocol which does not support any type of attachments.
> 
> As alternate way we may use internal SMTP server or 3P server to sending emails, but this will overcomplicate all the solution.

thanks for replying, I'm not a coder, not sure how to implement this (I have my own SMTP server), any pointers would be greatly appreciated

Thanks
