### ISSUE TITLE
White space in Registered City

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#40]
Hi,

If I enter a value of two words, separated with a white space, the part after (including) the white space disappears

Thanks

**Comment by d3vilh** [comment]
hello again,
Yes, Im replacing " " with "" as part of the code for names and VARs intentionally to simplify the certs generation with backend bash scripts.
As of now I recoment to use "_", "." or "-" and it depends on how critical this limitation to override in one of the future versions.

**Comment by d3vilh** [comment]
Hey @reamasesa 
This one is fixed in Dev as well. Same as Org Unit. 
Will combine in the next release all together with the rest bugs.

**Thanks for reporting!**

**Comment by reamasesa** [comment]
> Hey @reamasesa This one is fixed in Dev as well. Same as Org Unit. Will combine in the next release all together with the rest bugs.
> 
> **Thanks for reporting!**

Thank you, usually it's just "text" but sometimes people are picky about their city name not showing "properly" :) :) :)

**Comment by d3vilh** [comment]
Closed as fixed in [0.9.4.1](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9.4.1)
