### ISSUE TITLE
Client configuration menu issues

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#41]
Hi,

When I add/change a setting in the client Configuration=>OpenVPN Client section, doesn't matter if I delete the value, it stil lshows when I come back to the page or create a new certificate

I tried initializing all, dropping the DB, nothing helped so, as this is a test instance, I dropped the containers, cleaned the relevant directories and started the containers again

I also saw this message in the OpenVPN container logs
`openvpn  | 2023-12-06 12:57:25 Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).`

Thanks

* Let me know if you'd like further issues combined into one issue or separated issues
Thanks again for all your work with this

**Comment by d3vilh** [comment]
Hi @reamasesa 

> When I add/change a setting in the client Configuration=>OpenVPN Client section, doesn't matter if I delete the value, it stil lshows when I come back to the page or create a new certificate
> 
> I tried initializing all, dropping the DB, nothing helped so, as this is a test instance, I dropped the containers, cleaned the relevant directories and started the containers again

Could you share the version of container you are currently running.
It is very similar to [this issue fixed](https://github.com/d3vilh/openvpn-ui/issues/30#issuecomment-1769295093) in `0.9.4`.

It seems you may run on 0.9.3 which has bug with updating Client parameters into the DB.
you could check version with inspect: `docker inspect --format='{{json .Config.Labels}}' d3vilh/openvpn-ui:latest`

As I remember you are running x86 version, please confirm this as well. 
Meanwhile I'll build test server for testing this out more precisely.

**Comment by d3vilh** [comment]
This was fixed as well for [Raspberry-Gareway](https://github.com/d3vilh/raspberry-gateway/commit/6aecd6887fa77121bd6b144ab6c7aa04cbdd8501) and [openvpn-server](https://github.com/d3vilh/openvpn-server/commit/9af908ab9164fe2c4970b3de2ac604100557b31e)

Now it lists all the parameters correctly.

I'll rebuild openvpn-server container soon.

**Comment by reamasesa** [comment]
> Hi @reamasesa
> 
> > When I add/change a setting in the client Configuration=>OpenVPN Client section, doesn't matter if I delete the value, it stil lshows when I come back to the page or create a new certificate
> > I tried initializing all, dropping the DB, nothing helped so, as this is a test instance, I dropped the containers, cleaned the relevant directories and started the containers again
> 
> Could you share the version of container you are currently running. It is very similar to [this issue fixed](https://github.com/d3vilh/openvpn-ui/issues/30#issuecomment-1769295093) in `0.9.4`.
> 
> It seems you may run on 0.9.3 which has bug with updating Client parameters into the DB. you could check version with inspect: `docker inspect --format='{{json .Config.Labels}}' d3vilh/openvpn-ui:latest`
> 
> As I remember you are running x86 version, please confirm this as well. Meanwhile I'll build test server for testing this out more precisely.

Thanks for your help, I'm using version 0.9.4

`{"com.docker.compose.config-hash":"a5fad92df8ac8eed80296ba8f40f258fece07489c658ddfc171f6ca489d40f17","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:1c66c1cd78c00506e1400e9295906fa2928ef11bb474b737c2fde24603f3d55b","com.docker.compose.oneoff":"False","com.docker.compose.project":"openvpn","com.docker.compose.project.config_files":"/home/ubuntu/openvpn/docker-compose.yml","com.docker.compose.project.working_dir":"/home/ubuntu/openvpn","com.docker.compose.service":"openvpn-ui","com.docker.compose.version":"2.21.0","maintainer":"Mr.Philipp <d3vilh@github.com>","version":"0.9.4"}`

`{"com.docker.compose.config-hash":"64ac95f8d7f76437c7ae8d04272383e1738bc6fe0032751eb34b4102306922ba","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:a041fdda29064b9b9d3a51c569ea6e9c28a40e8070483162ead7b7686f5f741e","com.docker.compose.oneoff":"False","com.docker.compose.project":"openvpn","com.docker.compose.project.config_files":"/home/ubuntu/openvpn/docker-compose.yml","com.docker.compose.project.working_dir":"/home/ubuntu/openvpn","com.docker.compose.service":"openvpn","com.docker.compose.version":"2.21.0","maintainer":"Mr.Philipp <d3vilh@github.com>","version":"0.3"}`

**Comment by reamasesa** [comment]
By the way, I'm using `image: d3vilh/openvpn-server:0.4-amd64` but as you can see from the output above, it shows `"version":"0.3"`

**Comment by d3vilh** [comment]
OK, so we had bug #71 "Unable to set client config Proto..." which was fixed in [`0.9.5.4`](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9.5.4) release.

On top of this I did strategic design decision, to take client configuration parameters from the client.config when downloading generated Certificates. 

In all the versions before [`0.9.5.5`](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9.5.5) such parameters as `Proto`, `Auth`, `Cipher` were taken from server.config by default (also option to set it in Client configuration exists, but when downloading certs these params were taken form different DB table).

So, now you have to set these parameters as equal in the both Client and Server configuration page independently.

We will leave with this design and will see how much tickets will ba opened :)

Also I think it is better approach, as it gives a little bit more freedom for the configuration.

Bugfix is available in `main` branch, tested and will be included in future [`0.9.5.5`](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9.5.5) release on this weekend.
