### ISSUE TITLE
OpenVPN issue when missing /etc/openvpn/config/easy-rsa.vars

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#42]
Hi,

When I start a new, clean, containers, with `config` directory as volume, I get this message

`openvpn     | cp: can't stat '/etc/openvpn/config/easy-rsa.vars': No such file or directory
openvpn exited with code 1`

Placing an empty file before starting the containers resolves this

Thanks

**Comment by d3vilh** [comment]
Hi @reamasesa,
This is mandatory file to initiate PKI at the first OpenVPN container start, as it contains [default EasyRSA vars](https://github.com/d3vilh/openvpn-server/blob/main/config/easy-rsa.vars).

It is described in [Container Deployment details](https://github.com/d3vilh/openvpn-server#container-deployment-details) and would be created automatically if you'll use [OpenVPN-AWS](https://github.com/d3vilh/openvpn-aws) for x86 computers (it needs Ansible though but automates OpenVPN and UI setup).

**Comment by d3vilh** [comment]
This was fixed as well for [Raspberry-Gareway](https://github.com/d3vilh/raspberry-gateway/commit/6aecd6887fa77121bd6b144ab6c7aa04cbdd8501) and [openvpn-server](https://github.com/d3vilh/openvpn-server/commit/9af908ab9164fe2c4970b3de2ac604100557b31e)

Now it lists all the parameters correctly.

I'll rebuild openvpn-server container soon.

**Comment by reamasesa** [comment]
> Hi @reamasesa, This is mandatory file to initiate PKI at the first OpenVPN container start, as it contains [default EasyRSA vars](https://github.com/d3vilh/openvpn-server/blob/main/config/easy-rsa.vars).
> 
> It is described in [Container Deployment details](https://github.com/d3vilh/openvpn-server#container-deployment-details) and would be created automatically if you'll use [OpenVPN-AWS](https://github.com/d3vilh/openvpn-aws) for x86 computers (it needs Ansible though but automates OpenVPN and UI setup).

Thanks, sorry for the late replies, it's been hectic here
I re-read it, it's not quite clear if it should be created manually or not, I checked my notes and during all my tests I have created this file manually to check if the UI uses the variables in it, the only time I didn't create the file manually I got this error (which is not an issue as I now know :) )

**Comment by d3vilh** [comment]
@a-reznic[ here is nice WA](https://github.com/d3vilh/openvpn-server/issues/14#issuecomment-2063162458) for the same problem (wget the file).
Supposed to be fixed, but it seems not. Let me have a look on it.
