### ISSUE TITLE
Credits to authors

### ISSUE THREAD

**Issue by bugsyb** [d3vilh/openvpn-ui#43]
It would be really nice if initial authors of the code which is claimed here as yours, would be referenced.
For example:
https://github.com/bugsyb/openvpn-web-ui-docker-build
Which is effectively:
https://github.com/d3vilh/openvpn-ui/tree/main/build

And situations like maintainer entry replaced with your credentials with zero credit for others work. It is not only about my work, there's certainly many others who did a lot skipped and code is claimed as yours.

Just claiming others work as yours is no nice.

At the same time, all integrations put all together into one place is really good - thumbs up for that.

**Comment by bugsyb** [comment]
Good point, readme.md has been awaiting for an update for quite some time and it has been pushed out now.

Good work integrating so many elements on top of what Adam did, as it certainly took a lot of time and effort. Thanks for the work.

**Comment by permanutry** [comment]
Hey guys you both are awesome.
Nice tread btw. I also would like to be in credits somewhere, how can I participate 😁😎

Im kidding 😁 Merry Christmas to you all🎄🎄🎄
