### ISSUE TITLE
Port forwarding to client

### ISSUE THREAD

**Issue by namen3645** [d3vilh/openvpn-ui#46]
Ho to port forward to client?

**Comment by d3vilh** [comment]
Hi @namen3645, 
You should do it on the OpenVPN server side.
If you are running OpenVPN-UI in a couple with [openvpn-server](https://github.com/d3vilh/openvpn-server) container, [raspberry-gateway](https://github.com/d3vilh/raspberry-gateway) or [openvpn-aws](https://github.com/d3vilh/openvpn-aws), then you can use [`firewall-rules.sh`](https://github.com/d3vilh/openvpn-server/blob/main/fw-rules.sh) script to add any forwarding rules (how to do it described in [this sticked issue](https://github.com/d3vilh/openvpn-ui/issues/11).

For local installations, just use your iptables or ufw to add any permanent rules you would like.

**Comment by d3vilh** [comment]
Hi @namen3645, how are you doing today?
Would you let me know if you managed to apply forwarding?
