### ISSUE TITLE
possible to use the UI on existing vpn server installation ?

### ISSUE THREAD

**Issue by dberardo-com** [d3vilh/openvpn-ui#48]
i see that the project comes with its own docker image which i assume contains also the ovpn server part. but it is possible to use it on an existing environment that runs outside docker? and if so, should those 2 environments share the same filesystems or can the 2 run on separate machines (ie. gui on server 1 and ovpn legacy env on server 2 ) ?

cheers

**Comment by d3vilh** [comment]
Hi @dberardo-com,
Yes it is possible. You could clone repo, then go into `~/build/` directory and run `./standalone-install.sh` script for standalone build and installation.
[The issue #26 ](https://github.com/d3vilh/openvpn-ui/issues/26) has installation steps and logs.
Please be aware that standalone installation is currently supports supported Debian linux only. 

Post installation and UI start you have to go into "Configuration > OpenVPN UI" and set "OpenVPN ConfigPath" and "Easy-RSA ConfigPath" options accordingly. 
> Note that UI, at the moment takes server.conf and client.conf from /etc/openvpn/config subdirectory, so you have to copy files there and adjust server start config accordingly.
> In version 1 I'll update UI to take config just from the /etc/openvpn dir.

As for the different servers - this may work with OpenVPN server configuration and EasyRSA pki dir mounted over NFS to the server where OpenVPN UI is running. However, it was never tested. If you would test, please let me know results.

**Comment by thomas2108** [comment]
There are several minor issues, I discovered, when installing this on my standalone vpn server. If I remember right, this where
- location of server.conf and client conf - solved this using links
- required scripts in location /opt/scripts - solved using links
- required openvpn-ui location at /opt/openvpn-ui - solved using links
- scripts in "scripts" directory to i.e. restart openvpn only rely on docker - edited them ti restart service
- maybe more, don't remember, fixed several issues on the fly

but - cool project and really useful! Thanks d3vilh!

**Comment by d3vilh** [comment]
Hi @thomas2108 thank you for the reporting.
I'll keep the issue open until documentation update in `main` branch.

**Comment by jav-12** [comment]
I am also interested in this. I already have a working OpenVPN server with multiple users. I need a user interface to manage them properly.

**Comment by d3vilh** [comment]
> I already have a working OpenVPN server with multiple users.
Hi @jav-12 do you mean different server instances running on the same server?
If so, you could run different OpenVPN-Ui instances as well for every server instance you have.
All you need is to change ports and paths in `openvpn-ui/conf/app.conf` accordingly.

**Comment by jav-12** [comment]
Yes. I want to use the GUI on the server already used for the VPN.

**Comment by d3vilh** [comment]
If you have Docker env available on the server, you could run just openvpn-ui container as [Dockerfile](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#run-this-image-using-the-dockerfile) or [Docker-compose](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#running-this-image-with-docker-composeyml-file) with `volumes:` setup towards your server and easyrsa configuration files.

Alternatively is to build ui with `./standalone-install.sh` script.
It will build binaries for your arch and distro version, then you can use those binaries to run as a service or as application without any issue.

For both cases it is better to use some test environment before applying the solution on Prod environment.

**Comment by null-p01ntr** [comment]
> If you have Docker env available on the server, you could run just openvpn-ui container as [Dockerfile](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#run-this-image-using-the-dockerfile) or [Docker-compose](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#running-this-image-with-docker-composeyml-file) with `volumes:` setup towards your server and easyrsa configuration files.
> 
> [Alternatively](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#standalone-installation-without-docker-and-docker-compose) is to build ui with `./standalone-install.sh` script. It will build binaries for your arch and distro version, then you can use those binaries to run as a service or as application without any issue.
> 
> For both cases it is better to use some test environment before applying the solution on Prod environment.

hello, im also trying to install just the web UI. I have installed OpenVPN with PiVPN with default settings. Where and how should I set up the volumes exactly?

**Comment by d3vilh** [comment]
> hello, im also trying to install just the web UI. I have installed OpenVPN with PiVPN with default settings. Where and how should I set up the volumes exactly?

Hi @null-p01ntr ,
You have to follow the [standalone installation guide ](https://github.com/d3vilh/openvpn-ui?tab=readme-ov-file#standalone-installation-without-docker-and-docker-compose). Be precise with username and password vars.

Then just login and modify openvpnUI parameters to set where your openvpn server config dir is and easyrsa home directory.

I don't use PiVPN and [Rspberry-Gateway ](https://github.com/d3vilh/raspberry-gateway) is neat even on PiZero boards.
