### ISSUE TITLE
Access to the panel via API requests

### ISSUE THREAD

**Issue by jaygent** [d3vilh/openvpn-ui#50]
Access to the panel via API requests
Creating and deleting server access

**Comment by d3vilh** [comment]
Hi @jaygent 
OpenVPN-UI uses [OpenVPN management console](https://openvpn.net/community-resources/management-interface/) to retrieve connected users information and drop clients.

OpenVPN server also supports [REST APIs](https://openvpn.net/images/pdf/REST_API.pdf) as APIs to control server.

As of OpenVPN-UI APIs itself, I don't have any plans to implement it. 
However, if someone would like to implement and later maintain it -  welcome. I can give full access to this repo as it will benefit to the community a lot.

**Comment by jaygent** [comment]
ok

**Comment by class1cs** [comment]
how to access it? i researched a lot of sources, but found nothing but instruction for openvpn CWS.

**Comment by SilvioDoMine** [comment]
Is API open only to cloud? What about self hosted?
