### ISSUE TITLE
127.0.0.1:53 misbehaving

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#54]
Hi,

I have a vague recollection of this being resolved somehow but for the life of me, I can't remember how :(

![image](https://github.com/d3vilh/openvpn-ui/assets/1943175/9f823c50-dafb-4329-8f8b-642fe7b948af)
![image](https://github.com/d3vilh/openvpn-ui/assets/1943175/29edf483-481e-4f73-8791-dfaa5834c00f)

Thanks

**Comment by d3vilh** [comment]
Hi @reamasesa it happens when UI can't connect to OpenVPN Server management console. 

It should listen on all the openvpn container interfaces, so Ui will be able to restart sessions and see active connections.

Please check your `server.conf` for the `management 0.0.0.0 2080` line.

**Comment by reamasesa** [comment]
Hi,

It's already configured like this as default

![image](https://github.com/d3vilh/openvpn-ui/assets/1943175/15ed7d5f-8ce7-4087-9687-3cb0252f0bd5)

**Comment by d3vilh** [comment]
this error, in general, means OpenVPN UI can't find management interface by hostname "openvpn" which is internal to Docker environment. 
First is to check that openvpn container is running, then try to access it via openvpn-ui container with a hostname:
```bash
mrphil@d3pi1:~ $ sudo docker exec -it --user=root openvpn-ui bash -c "nc -zv openvpn 2080"
openvpn (172.26.0.2:2080) open
mrphil@d3pi1:~ $
```
and for sure, when you are changing management port of OpenVPN server, you have to restart server or its container.
