### ISSUE TITLE
Feature Request: Integrate SSO with Authentik

### ISSUE THREAD

**Issue by gotiee** [d3vilh/openvpn-ui#75]
Hi there,

First, thank you for the incredible work on this project. The graphical interface for OpenVPN is incredibly useful, and the existing user management system is quite helpful.

However, I believe the user management experience could be further enhanced by integrating a Single Sign-On (SSO) solution, such as Authentik. Here are a few reasons why I think this would be beneficial:

1. Improved Security: SSO solutions like Authentik offer advanced security features such as multi-factor authentication (MFA) and centralized user management, reducing the risk of security breaches.
2. Better User Experience: Users can log in with their existing credentials, eliminating the need to remember multiple usernames and passwords.
3. Simplified Administration: With SSO, administrators can manage user access and permissions more efficiently, ensuring that only authorized users have access to the VPN.

Suggested Implementation:

- Integrate the Authentik SSO provider into the existing user management system.
- Allow administrators to configure SSO settings via the graphical interface.
- Provide documentation and examples for setting up and using Authentik with the project.

I believe that this integration would greatly benefit many users and administrators by providing a more secure and user-friendly authentication method.

Thank you for considering this feature request. Please let me know if I can provide any further details or assist in any way.

Best regards,
Gauthier

**Comment by d3vilh** [comment]
Hi @gotiee,
This is very nice enhancement some people would like to be implemented, however it require some tome for development and existent functionality redesign. I'd be glad to include it, but not in the nearest future.
