### ISSUE TITLE
duplicate-cn

### ISSUE THREAD

**Issue by BliNeR-KeY** [d3vilh/openvpn-ui#77]
hello 
i have problem with duplicate-cn
for use same certs more users.
i have tested. 
connect  device1.. after i try connect other one disconect device1 and connect device2.

never connected both.

or maybe if have config have more devices 1 user.

**Comment by d3vilh** [comment]
Hi @BliNeR-KeY,
yes it is expected OpenVPN design, as it is peer to peer connection you can't use the same cert on different devices at the same time.
