### ISSUE TITLE
standalone-install.sh FATAL 0004 exit status 1

### ISSUE THREAD

**Issue by dwd1** [d3vilh/openvpn-ui#79]
...
Would you like to install OpenVPN-UI and qrencode? (y/n) y
Installing OpenVPN-UI and qrencode
Cloning qrencode into build directory
Cloning into 'qrencode'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 35 (delta 8), reused 31 (delta 8), pack-reused 0
Receiving objects: 100% (35/35), 26.88 KiB | 1.68 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Building and packing OpenVPN-UI
2024/06/01 20:04:49.531 [D]  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
2024/06/01 20:04:49 INFO     ▶ 0001 Getting bee latest version...
2024/06/01 20:04:49 INFO     ▶ 0002 Your bee are up to date
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.1.0

├── GoVersion : go1.21.5
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    :
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Saturday, 1 Jun 2024
2024/06/01 20:04:50.110 [D]  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.1.0
2024/06/01 20:04:50 INFO     ▶ 0001 Packaging application on '/home'...
2024/06/01 20:04:50 INFO     ▶ 0002 Building application (home)...
2024/06/01 20:04:50 INFO     ▶ 0003 Using: GOOS=linux GOARCH=amd64
package .: no Go files in /home
2024/06/01 20:04:50 FATAL    ▶ 0004 exit status 1
Building qrencode
./standalone-install.sh: line 111: cd: build/qrencode: No such file or directory
cannot find package "main.go" in any of:
        /usr/local/go/src/main.go (from $GOROOT)
        /home/openvpn/go/src/main.go (from $GOPATH)
chmod: cannot access 'qrencode': No such file or directory
Moving qrencode to GOPATH
mv: cannot stat 'qrencode': No such file or directory
All done.

**Comment by d3vilh** [comment]
HI @dwd1,
You have to clone whole repo, then go into `build` directory and from this directory run `./standalone-install.sh` script.
Then it will process correctly.
