### ISSUE TITLE
creating user in server

### ISSUE THREAD

**Issue by elyarsa** [d3vilh/openvpn-ui#86]
Hello
How can I create a user without using ui
I need to create user in the server

**Comment by d3vilh** [comment]
Hi @elyarsa,
Do you need user inside the openvpn-ui or openvpn-server image or just regular user of your server?

**Comment by elyarsa** [comment]
Thanks for your response

I want to create a telegram bot that sends command to server and creates new certificate user and sends .ovpn file to user
and I need openvpn-ui show that user in the certificates menu

I tested this command : sudo docker exec openvpn bash /opt/app/bin/genclient.sh test
but I got this error :

grep: ../openvpn-ui/conf/app.conf: No such file or directory
grep: ../openvpn-ui/conf/app.conf: No such file or directory
EasyRSA path:  OVPN path: 
Patching easy-rsa.3.1.1 openssl-easyrsa.cnf...
sed: /pki/openssl-easyrsa.cnf: No such file or directory

**Comment by d3vilh** [comment]
> I tested this command : sudo docker exec openvpn bash /opt/app/bin/genclient.sh test

You better to stick to openvpn-ui image and pass all the EasyRSA vars as env. Try this command it should work fine:
```bash
sudo docker exec -e EASYRSA_CERT_EXPIRE=181 \
                 -e EASYRSA_REQ_EMAIL=kak@popo.ua \
                 -e EASYRSA_REQ_COUNTRY=UA \
                 -e EASYRSA_REQ_PROVINCE=KY \
                 -e EASYRSA_REQ_CITY=Kyiv \
                 -e EASYRSA_REQ_ORG=home \
                 -e EASYRSA_REQ_OU=kitchen \
                 openvpn-ui bash -c "cd /opt/scripts && ./genclient.sh test1"
```

**Comment by elyarsa** [comment]
Thank you
It worked
